### ISSUE TITLE
Add support for hwloc 2.x or fix build scripts to install a particular version

### ISSUE THREAD

**Issue by juliohm** [JuliaParallel/Hwloc.jl#16]
As discussed in https://github.com/travis-ci/travis-ci/issues/9345, some machines are segfaulting because a newer version of hwloc is being installed (2.x). We need to fix the `deps.jl` file and take care of these ABI changes.

@tkelman and @eschnett, your help is highly appreciated. I don't have a Mac myself, it is hard to debug this quickly. Nor I have the experience to wrap C APIs in Julia.

**Comment by eschnett** [comment]
The function to call is `hwloc_get_api_version`. This function takes no parameter and returns an `unsigned`, which hex-encodes the version number. For example, version 2.0.0 corresponds to the value `0x00020000`; version 1.11.6 is `0x00010b06`.

**Comment by juliohm** [comment]
Nice, now the question is how to branch the code and support 1.x and 2.x at the same time. Is that the goal?

**Comment by eschnett** [comment]
This is resolved as of `hwloc 1.0.0`.
