### ISSUE TITLE
Release 1.1.0 as stable version

### ISSUE THREAD

**Issue by racinmat** [JuliaParallel/Hwloc.jl#34]
Hi, the latest version published in registry is 1.0.3. This is not usin Hwloc_jll so it directly accesses github.com instead of using package server. 
Could you please release 1.1.0 as a stable version? 
Thanks much.

**Comment by eschnett** [comment]
See https://github.com/JuliaRegistries/General/pull/26184

**Comment by racinmat** [comment]
Thank you!
