### ISSUE TITLE
No caches found on WSL2

### ISSUE THREAD

**Issue by hsgg** [JuliaParallel/Hwloc.jl#36]
`Hwloc.jl` does not find the L1 and L2 caches when running on the Windows Subsystem for Linux 2 (WSL2):
```
julia> Hwloc.topology_load()
D0: L0 P0 Machine  
    D1: L0 P0 Package  
        D2: L0 P0 Core  
            D3: L0 P0 PU  
            D3: L1 P1 PU  
        D2: L1 P1 Core  
            D3: L2 P2 PU  
            D3: L3 P3 PU  
        D2: L2 P2 Core  
            D3: L4 P4 PU  
            D3: L5 P5 PU  
        D2: L3 P3 Core  
            D3: L6 P6 PU  
            D3: L7 P7 PU  
        D2: L4 P4 Core  
            D3: L8 P8 PU  
            D3: L9 P9 PU  
        D2: L5 P5 Core  
            D3: L10 P10 PU  
            D3: L11 P11 PU  
        D2: L6 P6 Core  
            D3: L12 P12 PU  
            D3: L13 P13 PU  
        D2: L7 P7 Core  
            D3: L14 P14 PU  
            D3: L15 P15 PU  
```

`/proc/cpuinfo` looks normal, as far as I can tell, except that according to [Intel Marketing](https://www.intel.com/content/www/us/en/products/processors/core/i9-processors/i9-9980hk.html) this CPU should have 16 MB cache total:
```
...
processor	: 15
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
stepping	: 13
microcode	: 0xffffffff
cpu MHz		: 2400.000
cache size	: 256 KB
physical id	: 0
siblings	: 16
core id		: 7
cpu cores	: 8
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 6
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt ibrs ibpb stibp ssbd
bogomips	: 4800.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

The system I am running is Ubuntu-20.04 on Windows under WSL2.
```
$ uname -a
Linux hypergeometric 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Ultimately, this makes [DifferentialEquations.jl](https://github.com/SciML/DifferentialEquations.jl) fail to precompile, as I reported [here](https://github.com/chriselrod/VectorizationBase.jl/issues/27).

**Comment by chriselrod** [comment]
The only thing LoopVectorization actually wants for now is the cacheline size (but it's reasonably likely I'll have it eventually start doing cache-tiling as well, in which case it'd want things like l1 and/or l2 size).
As a workaround, I'll have it assume it is 64 bytes if the information is unavailable. 64 is common, but some CPUs like the the A64FX, which [has 256 byte cachelines](https://www.fujitsu.com/downloads/SUPER/a64fx/a64fx_datasheet.pdf) (and many times the memory bandwidth of any x86 cpu), can have very different values.

**Comment by eschnett** [comment]
Unfortunately I don't have access to a WSL2 system, so I can't try myself.

Can you install the Ubuntu `hwloc-nox` (or `hwloc`) package, and run `hwloc-ls` and/or `hwloc-info` there? This would tell us whether the problem is in hwloc itself or in our wrapper.

Can you also report which version of `hwloc` you installed? The most recent one is 2.2, I believe.

**Comment by eschnett** [comment]
@hsgg Regarding the cache size: `/proc/cpuinfo` probably reports the L2 cache size, which is specific to each core. The larger 16 MB cache is the L3 cache, which is shared among all cores on a CPU. In other words, this might be as designed.

**Comment by chriselrod** [comment]
[Wikichip](https://en.wikichip.org/wiki/intel/core_i9/i9-9980hk) normally provides nice summaries if you want to look up individual CPUs/CPU families.
Your CPU has 32KiB L1 and 512KiB L2.

**Comment by hsgg** [comment]
> Can you install the Ubuntu `hwloc-nox` (or `hwloc`) package, and run `hwloc-ls` and/or `hwloc-info` there? This would tell us whether the problem is in hwloc itself or in our wrapper.
> 
> Can you also report which version of `hwloc` you installed? The most recent one is 2.2, I believe.

Yes, looks like a bug in `hwloc`. I have `hwloc-nox` version `2.1.0` installed through the Ubuntu repositories. I also downloaded latest git master version `2.5.0a1-git` and got
```
$ ./hwloc-info 
depth 0:           1 Machine (type #0)
 depth 1:          1 Package (type #1)
  depth 2:         8 Core (type #2)
   depth 3:        16 PU (type #3)
Special depth -3:  1 NUMANode (type #13)
```
and
```
$ hwloc-ls 
Machine (64GB total) + Package L#0
  NUMANode L#0 (P#0 64GB)
  Core L#0
    PU L#0 (P#0)
    PU L#1 (P#1)
  Core L#1
    PU L#2 (P#2)
    PU L#3 (P#3)
  Core L#2
    PU L#4 (P#4)
    PU L#5 (P#5)
  Core L#3
    PU L#6 (P#6)
    PU L#7 (P#7)
  Core L#4
    PU L#8 (P#8)
    PU L#9 (P#9)
  Core L#5
    PU L#10 (P#10)
    PU L#11 (P#11)
  Core L#6
    PU L#12 (P#12)
    PU L#13 (P#13)
  Core L#7
    PU L#14 (P#14)
    PU L#15 (P#15)
```
I intend to file a bug with [hwloc](https://github.com/open-mpi/hwloc) in the next few days, and will post the link once I do.

@chriselrod , using cacheline=64 seems like a sane and simple workaround to me.

Thank you both for your help!

**Comment by carstenbauer** [comment]
I guess this can be closed because it is an upstream bug.

Regarding cache(line) sizes: there is #47 and #28 which gives access to the L1/L2/L3 cache sizes. I can also add a `cachlinesize` function (similar to what CpuId.jl has) which gives easy access to the cacheline sizes as reported by hwloc.

**Comment by carstenbauer** [comment]
Upstream issue. By now, we also have:

```Julia
julia> cachelinesize()
(L1 = 64, L2 = 64, L3 = 64)

julia> cachesize()
(L1 = 32768, L2 = 262144, L3 = 12582912)
```
