### ISSUE TITLE
topology_load errors due to unimplemented groups

### ISSUE THREAD

**Issue by jmulcahy** [JuliaParallel/Hwloc.jl#38]
I'm receiving an error when I call `topology_load` which traces back to this line: https://github.com/JuliaParallel/Hwloc.jl/blob/master/src/Hwloc.jl#L404.

The machine is a dual socket server with two AMD Epyc 7702s. I tried the same command on a dual socket Intel server and an AMD 5900X desktop, neither of which didn't ran into the error. I know very little about Hwloc, but if I had to guess the AMD server is showing up as having groups due to the combination of two sockets and AMD's chiplet architecture.

I'm trying to use this package as part of LoopVectorization.jl, and the error is causing that package to fall back to a generic topology. I don't know that LoopVectorization.jl works with groups anyway, but getting support in Hwloc.jl would be the first step I suppose.

**Comment by eschnett** [comment]
I added the missing functionality into my Hwloc.jl fork at <https://github.com/eschnett/Hwloc.jl>. The change seems simple, but I couldn't test it. Let me know whether it works (and where it gets stuck next).

I think hwloc offers functionality to save and restore topologies, but I've never used this feature. If so, this might be a way for me to look at your topology. Getting shell access to such an AMD system would be another option (if your system is publicly accessible – I have experience with quite a few HPC systems).

Could you also install hwloc (`sudo apt install hwloc` or similar) and show me the output of `lstopo` or similar?

**Comment by jmulcahy** [comment]
Thanks for taking a look at this. Your fork appears to just work without any more modification. The AMD server shows up as having four groups per processor, which I guess makes sense given the core configuration listed for the 7702 here: https://en.wikipedia.org/wiki/Epyc#Second_generation_Epyc_(Rome).

The unit tests pass everywhere I've tried: Windows AMD 5900X, Ubuntu Intel dual socket server, Ubuntu dual AMD 7702 server, Intel Macbook Pro.
