### ISSUE TITLE
Using Hwloc failed. Please file an issue with the above warning

### ISSUE THREAD

**Issue by guyvdbroeck** [JuliaParallel/Hwloc.jl#43]
┌ Warning: AssertionError("obj.type_ >= 0 && obj.type_ < length(obj_types)")
└ @ VectorizationBase ~/.julia/packages/VectorizationBase/bYkVf/src/topology.jl:9
┌ Warning:     Using Hwloc failed. Please file an issue with the above warning at: https://github.com/JuliaParallel/Hwloc.jl
│     Proceeding with generic topology assumptions. This may result in reduced performance.
└ @ VectorizationBase ~/.julia/packages/VectorizationBase/bYkVf/src/topology.jl:10

**Comment by eschnett** [comment]
Thanks for the report. To investigate, I need a bit more information. Which version of the `hwloc` library were you using? You find this output by typing `status -m` into Julia in package manager mode, and looking at both the `Hwloc` and `Hwloc_jll` libraries.

You should see versions `1.3.0` and `2.4.1`, respectively.

If you are using older versions, can you try updating?

**Comment by guyvdbroeck** [comment]
I was using
  [0e44f5e4] Hwloc v1.2.0
  [e33a78d0] Hwloc_jll v2.4.0+0
Now, after upgrading to 
  [0e44f5e4] Hwloc v1.3.0
  [e33a78d0] Hwloc_jll v2.4.1+0
I no longer see the warning. I will let you know if it ever comes back.

**Comment by eschnett** [comment]
Thanks! I'll close the issue in the mean time; please reopen if necessary.
