### ISSUE TITLE
Darwin ARM: libhwloc not defined

### ISSUE THREAD

**Issue by lukeburns** [JuliaParallel/Hwloc.jl#44]
Running native Julia v1.7 on Mac M1

Also see https://github.com/JuliaMath/FFTW.jl/issues/187

```jl
julia> versioninfo()
Julia Version 1.7.0-DEV.720
Commit 5515893eac (2021-03-17 18:47 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin20.2.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, cyclone)

pkg> add Hwloc_jll
...
julia> using Hwloc
[ Info: Precompiling Hwloc [0e44f5e4-bd66-52a0-8798-143a42290a1d]
ERROR: LoadError: UndefVarError: libhwloc not defined
```

**Comment by giordano** [comment]
Meta issue about building JLL packages for the new platform: https://github.com/JuliaPackaging/Yggdrasil/issues/2763.

**Comment by mcabbott** [comment]
Note that there is now a v2.5 upstream: https://www.open-mpi.org/software/hwloc/v2.5/

The current https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl uses version v2.4.1 https://github.com/JuliaPackaging/Yggdrasil/blob/master/H/Hwloc/build_tarballs.jl . 

As described here: https://github.com/JuliaPackaging/Yggdrasil/issues/2763#issue-849393008, the easiest way to support ARM is to make a new release of Hwloc_jll.jl which only supports Julia 1.6, and the version of this jll can still match the upstream library.

This package does not seem to bound the jll version: https://github.com/JuliaParallel/Hwloc.jl/blob/master/Project.toml . So no new release would be needed here.

**Comment by giordano** [comment]
Fixed by https://github.com/JuliaPackaging/Yggdrasil/pull/3190.  Note that tests will fail because `CpuId.jl` isn't [ARM-friendly](https://github.com/m-j-w/CpuId.jl/issues/39)
