### ISSUE TITLE
Tag new version for Julia v0.6

### ISSUE THREAD

**Issue by juliohm** [JuliaParallel/Hwloc.jl#5]
Could you please fix the remaining warnings and tag a new version for Julia v0.6?

**Comment by eschnett** [comment]
Unfortunately, I haven't followed the Julia 0.6 development. I'd be happy to accept a patch.

**Comment by juliohm** [comment]
Thank you @eschnett , will work on it today.

**Comment by juliohm** [comment]
@eschnett the warnings are already fixed on master, I think you just need to tag a new version.

**Comment by eschnett** [comment]
I opened a pull request for `METADATA`.

**Comment by juliohm** [comment]
This should be fixed by now. Thank you @eschnett.
