### ISSUE TITLE
Drop hwloc 1.x support

### ISSUE THREAD

**Issue by carstenbauer** [JuliaParallel/Hwloc.jl#50]
I'm in the process of adding support for a few more of hwlocs features to our Julia wrapper (see #46 for example). Hereby I'm focusing on hwloc versions 2.x which use the data layout `hwloc_obj_v2` instead of `hwloc_obj_v1` used by versions 1.x. Supporting both is obviously more work and, for some features, not possible, which would mean that we couldn't add those.

In this issue, I'm proposing to drop support for hwloc 1.x to facilitate maintenance and development. I think this is justified because:

1) The last 1.x release, 1.11, was released in 2016, so ~5 years ago. The latest patch release for this minor version, 1.11.12-1, was released in 01/2019, so ~2 years ago.
2) We seem to only support Julia 1.3 and higher means that hwloc 2.x is provided by [Hwloc_jll](https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl) anyways.

Opinions?

**Comment by eschnett** [comment]
I agree. Let's drop support for hwloc 1.x.

**Comment by carstenbauer** [comment]
Dropped in #53 (future 2.0).
