### ISSUE TITLE
`cachesize()` doesn't work on A64FX

### ISSUE THREAD

**Issue by giordano** [JuliaParallel/Hwloc.jl#65]
```julia
julia> Hwloc.cachesize()
ERROR: Your system doesn't seem to have an L1 cache.
Stacktrace:
 [1] cachesize()
   @ Hwloc ~/.julia/packages/Hwloc/AAKOv/src/highlevel_api.jl:203
 [2] top-level scope
   @ REPL[27]:1
```

CC: @vchuravy

**Comment by giordano** [comment]
Seems to be an upstream issue: https://github.com/open-mpi/hwloc/issues/553

**Comment by bgoglin** [comment]
It's a firmware issue, it doesn't expose any cache info, hwloc has no way to find it. Julia shouldn't assume caches always exist, there are some other platforms with the same limitation.

**Comment by giordano** [comment]
> It's a firmware issue, it doesn't expose any cache info, hwloc has no way to find it.

Ok, thanks for the information!

> Julia shouldn't assume caches always exist, there are some other platforms with the same limitation.

Julia, as the language, has nothing to do with it: this is a third-party package.  And the function `cachesize()` is simply throwing an error because no cache information was found: https://github.com/JuliaParallel/Hwloc.jl/blob/a5bb9f6795f41f288ee4dd6d6fa0ff30ce8b2131/src/highlevel_api.jl#L230 which a decent thing to do when the requested information cannot be provided. An alternative could be to return a sentinel value like `nothing` and let the user handle it, but this is just a matter of choice how the shape the API, I don't see the wrong assumption here.

**Comment by carstenbauer** [comment]
There is nothing we can do about it here on the Julia side. And given what @bgoglin said, there also seems to be no way to fix this in hwloc itself. For this reason, I'm going to close this.
