### ISSUE TITLE
Configure AttoBot for Hwloc.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaParallel/Hwloc.jl#8]
Hi @eschnett,

I found out that I cannot configure AttoBot myself because I am not a member of JuliaParallel. Could you please follow their instructions to configure the bot? https://github.com/attobot/attobot

AttoBot is the modern way of tagging versions in Julia packages. It saves us a lot of headache.

**Comment by juliohm** [comment]
@andreasnoack @vchuravy @ViralBShah could you please help with this issue? I don't have the privileges to fix it myself.

**Comment by Keno** [comment]
attobot is set up for this repo.

**Comment by juliohm** [comment]
Thanks, I will try to tag then.
